x-common: &common
  env_file:
    - ./llama-cpp.env
  restart: unless-stopped
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:9931/health" ]
    interval: 30s
    timeout: 5s
    retries: 3

services:
  llama-cpp-gpu:
    <<: *common
    image: ghcr.io/ggml-org/llama.cpp:server-cuda13
    container_name: llama-cpp-gpu
    ports:
      - "9931:9931"
    volumes:
      # - ../models:/models
      - /home/mika/.cache/huggingface/hub:/root/.cache/huggingface/hub
      - ./config.ini:/etc/llama.cpp/config.ini:ro
      - ./preset-gpu.ini:/etc/llama.cpp/preset.ini:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
  llama-cpp-cpu:
    <<: *common
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: llama-cpp-cpu
    ports:
      - "9932:9931"
    volumes:
      # - ../models:/models
      - /home/mika/.cache/huggingface/hub:/root/.cache/huggingface/hub
      - ./config.ini:/etc/llama.cpp/config.ini:ro
      - ./preset-cpu.ini:/etc/llama.cpp/preset.ini:ro
