version = 1

[google/gemma-4-26b-a4b-qat]
hf = unsloth/gemma-4-26B-A4B-it-qat-GGUF:UD-Q4_K_XL
; Maximum without no-mmproj-offload
; ctx-size = 30208
ctx-size = 75000
fit = off
load-on-startup = true
n-gpu-layers = all
no-mmproj-offload = 1
spec-type = draft-mtp
spec-draft-n-max = 2
; Model parameters
; https://unsloth.ai/docs/models/gemma-4/qat#llama-server-deployment
temp = 1.0
; top-k is not supported on ROCm. This error message is emitted regardless of whether the top-k option is set.
; llama_sampler_backend_support: device 'ROCm0' does not have support for op TOP_K needed for sampler 'top-k'
; top-k = 64
top-p = 0.95
