version = 1

[llmfan46/gemma-4-26B-A4B-it-qat-q4_0-uncensored-heretic-GGUF]
hf = llmfan46/gemma-4-26B-A4B-it-qat-q4_0-uncensored-heretic-GGUF:Q4_0
; mmproj = /models/llmfan46/gemma-4-26B-A4B-it-qat-q4_0-uncensored-heretic-GGUF/gemma-4-26B-A4B-it-qat-q4_0-uncensored-heretic-mmproj-BF16.gguf
; model = /models/llmfan46/gemma-4-26B-A4B-it-qat-q4_0-uncensored-heretic-GGUF/gemma-4-26B-A4B-it-qat-q4_0-uncensored-heretic-Q4_0.gguf
ctx-size = 50000
load-mode = mmap+mlock
load-on-startup = true
# spec-type = draft-mtp

[Qwen/Qwen3.8-27B]
; hf = lmstudio-community/Qwen3.8-27B-GGUF:Q4_K_M
hf = unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_M
; mmproj = /models/lmstudio-community/Qwen3.8-27B-GGUF/mmproj-Qwen3.8-27B-BF16.gguf
; model = /models/lmstudio-community/Qwen3.8-27B-GGUF/Qwen3.8-27B-Q4_K_M.gguf
ctx-size = 50000
load-mode = mmap+mlock
load-on-startup = true
spec-type = draft-mtp
; Model parameters
; min-p = 0.0
; temp = 1.0
; top-k = 20
; top-p = 0.95
