version = 1

[google/gemma-4-26b-a4b-qat]
; Google's official version
; hf = google/gemma-4-26B-A4B-it-qat-q4_0-gguf:Q4_0
; hf-repo-draft = google/gemma-4-26B-A4B-it-assistant
; Unsloth with MTP
hf = unsloth/gemma-4-26B-A4B-it-qat-GGUF:UD-Q4_K_XL
; model = /models/google/
; model-draft =
ctx-size = 50000
load-on-startup = true
n-gpu-layers = auto
no-mmproj-offload = 1
spec-type = draft-mtp
spec-draft-n-max = 2
; Model parameters
; temp = 1.0
; top-k = 0.95
; top-p = 0.95
