version = 1

[*]
host = 0.0.0.0
kv-unified = 1
; Each model takes almost all of the VRAM, so only one is loaded at a time.
; Requesting the other model unloads the loaded one.
models-max = 1
models-preset = /etc/llama.cpp/preset.ini
no-ui = 1
port = 9931
; verbosity = 3
