version = 1

[google/gemma-4-31b-qat]
hf = unsloth/gemma-4-31B-it-qat-GGUF:UD-Q4_K_XL
ctx-size = 50000
; ctx-size = 100000
fit = off
; load-mode = dio
load-mode = none
load-on-startup = true
; Total layers = 60
; n-gpu-layers = all
n-gpu-layers = 53
; This is slow
; n-gpu-layers = 43
no-mmproj-offload = 1
parallel = 1
spec-draft-n-max = 2
spec-type = draft-mtp
