version = 1

[Qwen/Qwen3.8-27B]
hf = unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_M
ctx-size = 50000
load-mode = dio
load-on-startup = true
n-gpu-layers = all
spec-draft-n-max = 2
spec-type = draft-mtp
; Model parameters
; https://unsloth.ai/docs/models/qwen3.8#run-qwen3.8-in-llama.cpp
min-p = 0.0
temp = 1.0
top-k = 20
top-p = 0.95
